### PR TITLE
fix wxpython api change

### PR DESCRIPTION
**Pull request by machsix**

### CODE REVIEW

**Review by eliben — CHANGES_REQUESTED** [review]
Thanks.
Can you please separate out the whitespace changes from the actual API changes? Otherwise it's really hard to see where the substantial change is in this PR

**Comment by machsix** [comment]
> Thanks.
> Can you please separate out the whitespace changes from the actual API changes? Otherwise it's really hard to see where the substantial change is in this PR

whitespace change is removed

**Comment by eliben** [comment]
What version of Python did you test it with?

**Review by eliben — APPROVED** [review]

**Comment by eliben** [comment]
Thanks, I verified it works with python 3.8 and the latest wx

**Pull request merged**
